export const initialSidebarData = [
  {
    id: "topic-1",
    type: "topic",
    title: "Module 1: Introduction to Python",
    expanded: true,
    children: [
      { id: "page-1", type: "page", title: "What is Python?" },
      { id: "page-2", type: "page", title: "Installing Python & VS Code" },
      { id: "page-3", type: "page", title: "Running Python scripts" },
      { id: "page-4", type: "page", title: "Python syntax basics" },
    ],
  },
  {
    id: "topic-2",
    type: "topic",
    title: "Module 2: Variables & Data Types",
    expanded: true,
    children: [
      { id: "page-5", type: "page", title: "Variables and naming rules" },
      { id: "page-6", type: "page", title: "Numbers (int, float)" },
      { id: "page-7", type: "page", title: "Type casting" },
      { id: "test-1", type: "test", title: "Quiz 2" },
    ],
  },
  { id: "page-8", type: "page", title: "Common exceptions" },
  {
    id: "topic-3",
    type: "topic",
    title: "Module 3: Operators & Expressions",
    expanded: false,
    children: [],
  },
  {
    id: "topic-4",
    type: "topic",
    title: "Module 4: Control Flow",
    expanded: true,
    children: [
      { id: "page-9", type: "page", title: "if, elif, else" },
      { id: "page-10", type: "page", title: "Nested conditions" },
      { id: "page-11", type: "page", title: "match-case (optional advanced)" },
      { id: "test-2", type: "test", title: "Quiz 4" },
    ],
  },
  {
    id: "topic-5",
    type: "topic",
    title: "Module 5: Loops",
    expanded: false,
    children: [],
  },
  {
    id: "topic-6",
    type: "topic",
    title: "Module 6: Functions",
    expanded: false,
    children: [],
  },
  { id: "test-3", type: "test", title: "Final test" },
];
